### ISSUE TITLE
How would english people pronounce "Liso"...?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/liso#1]
@iteles how would _english_ (or other non-Latin-language speakers) people pronounce this?

**Comment by iteles** [comment]
Pretty sure it would be _Laizoe_ or _Lízoe_ depending on how proficient they are :wink:

**Comment by nelsonic** [comment]
But not _lie_-zoh tho...?

**Comment by iteles** [comment]
Ah, '_lai_-zoe' is my way of writing '_lie_-zoh' (guess I was reading the _lai_ in Portuguese)

**Comment by nelsonic** [comment]
So would english-speakers miss-pronounce it...? 
Do we need to add a (pronounced "_Lee's oh_") to the readme for clarity?

**Comment by iteles** [comment]
I don't think people will associate it with the word _lie_ though if that's the fear. But yes, I'd add the 'pronounced' statement for clarity!

**Comment by nelsonic** [comment]
Cool. done. _thanks_! :wink:
